### ISSUE TITLE
Easier install by using init.lua?!

### ISSUE THREAD

**Issue by blueyed** [stefano-m/awesome-pulseaudio_widget#2] opened 2017-07-15 21:35 UTC
It would be easier to install it from a source checkout if there was a `init.lua` file/symlink.

**Comment by stefano-m** [comment] 2017-07-15 21:58
Hi, I think you can symlink `pulseaudio_widget.lua` in your `~/.config/awesome` directory and that should be enough.
In my `~/.zprofile` file I have the following lines to ensure that the local lua path where `luarocks install --local` puts the installed modules:

```shell
if (( $+commands[luarocks] )); then
    eval `luarocks path --bin`
fi
```

I guess that something similar would work for bash too, e.g.

```shell
if [[ -n "`which luarocks 2>/dev/null`" ]]; then
    eval `luarocks path --bin`
fi
```

Can you confirm what works for you please?

I will update the README with that information.

Many thanks.

**Comment by stefano-m** [comment] 2017-07-15 22:06
I've just realized that you may need to symlink the widget's dependencies too though: [`pulseaudio_dbus`](http://luarocks.org/modules/stefano-m/pulseaudio_dbus) and [`dbus_proxy`](http://luarocks.org/modules/stefano-m/dbus_proxy).

**Comment by stefano-m** [comment] 2017-07-16 12:08
@blueyed I have updated the README with more information about installing locally with `luarocks`. I think that that should be enough to address this issue.

I will wait a bit for your feedback on this before closing the issue.

Thanks.

**Comment by stefano-m** [comment] 2017-07-24 14:07
@blueyed I am now going to closing this issue since it should have been fixed by updating the documentation. Feel free to reopen it and continue the discussion if you think that the issue is still there.

**Closed as completed** 2017-07-24 14:07 UTC
Labels: question
